### ISSUE TITLE
Failed to find module: "nativescript-svg", relative to: /app/tns_modules/

### ISSUE THREAD

**Issue by nicHoch** [peoplewareDo/nativescript-svg#1]
Hi i would like to use the plugin but it failed constantly.

is there a sample app to test it?

Nicky

**Comment by victorsosa** [comment]
Hi, 
Right now I don't have a demo; Could you at least post the complete log and the snippet code? also it will be helpful the env info like nativescript version and android version, etc.

That seems like a deploy issue in you environment '/app/tns_modules/' it not the place of the plugin; 
Did you run `tns plugin add nativescript-svg`?

**Comment by nicHoch** [comment]
the plugin is installed and i see the  `nativescript-svg` folder in the `node_module` folder.

so far i only require the module:

`var SVG  = require("nativescript-svg");` 

The error log is:
```
com.tns.NativeScriptException: Failed to find module: "nativescript-svg", relative to: /app/tns_modules/
	at com.tns.Module.resolvePathHelper(Module.java:220)
	at com.tns.Module.resolvePath(Module.java:60)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
	at com.tns.Runtime.callJSMethod(Runtime.java:712)
	at com.tns.Runtime.callJSMethod(Runtime.java:693)
	at com.tns.Runtime.callJSMethod(Runtime.java:683)
	at com.tns.gen.java.lang.Runnable_ftns_modules_timer_timer_l15_c20__.run(Runnable_ftns_modules_timer_timer_l15_c20__.java:10)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5001)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteI
```

```
tns-android": {
      "version": "2.0.0"
    }

 "tns-core-modules": "^2.0.1",
 "typescript": "^1.8.10"
```

**Comment by victorsosa** [comment]
FYI, I am working in a fix for this

**Comment by victorsosa** [comment]
Hi Nicky,

The fix for this issue is up in v1.0.5; you can download it any time.
Thank you, for you details on the issue.

**Comment by nicHoch** [comment]
Hi Victor

thanks for the next version but it is still not working:
Now the plugin can be required but any other image defined in xml crashes.
Do you override some core methods?

Why brings the plugin its own node_modules folder with a tns-core-module?

Do you know about the template how to create a nativescript plugin by Nathan Walker.
Maybe it will help you:

https://github.com/NathanWalker/nativescript-plugin-seed

```
com.tns.NativeScriptException: 
Calling js method run failed

Error: Building UI from XML. @file:///app/pages/home/home.xml:19:21
 ���imageSource.isFileOrResourcePath is not a function
File: "/data/data/com.thecrag.tca/files/app/tns_modules/ui/builder/builder.js, line: 156, column: 20

StackTrace: 
	Frame: function:'', file:'/data/data/com.thecrag.tca/files/app/tns_modules/ui/builder/builder.js', line: 156, column: 21
	Frame: function:'', file:'/data/data/com.thecrag.tca/files/app/tns_modules/xml/xml.js', line: 148, column: 13
	Frame: function:'EasySAXParser.parse', file:'/data/data/com.thecrag.tca/files/app/tns_modules/js-libs/easysax/easysax.js', line: 751, column: 23
	Frame: function:'XmlParser.parse', file:'/data/data/com.thecrag.tca/files/app/tns_modules/xml/xml.js', line: 195, column: 22
	Frame: function:'XmlStringParser.parse', file:'/data/data/com.thecrag.tca/files/app/tns_modules/ui/builder/builder.js', line: 162, column: 27
	Frame: function:'parseInternal', file:'/data/data/com.thecrag.tca/files/ap
```

**Comment by victorsosa** [comment]
Thanks for the tip.

Yes I am extend the ImageSource. Brings the plugin its own node_modules folder with a tns-core-module was a mistake, I am going to remove it.

Let me see you app/pages/home/home.xml file.

**Comment by victorsosa** [comment]
but any other image defined in xml crashes. Got you..

**Comment by victorsosa** [comment]
Hi Nicky,

The fix for this issue is up in v1.0.7; you can download it any time.
Thank you, for you details on the issue and sorry for all the trouble.

**Comment by victorsosa** [comment]
@nicHoch This is completed and tested on v1.0.11. I will upload an simple demo to repo soon.

Thanks for you help.

**Comment by nicHoch** [comment]
Hi Victor

i am looking forward to the demo i tried a bit the new version, but i just can not figure out how to connect the svg.ImageSource to a image in the view.

`svgParser.loadFromData('<svg height="100" width="100"><circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" /></svg> '));`

that will return true but how can i display the image?
Calling the toBase64String() method crashes the app.
Nicky

**Comment by victorsosa** [comment]
HI, @nicHoch 
the demo is in the repo; for how to connect the svg.ImageSource to a imageView in android, right now you have to do it by you self using an imageView class in android. I am working in a new nativescript xml component so this step can be avoided . You by now can try to load the svg.ImageSource.android by getting the drawable picture from it and put it in an imageView class, like in the example below from stackoverflow.

[svg on android image view | https://stackoverflow.com/questions/28215625/androidload-svg-file-from-web-and-show-it-on-image-view]

For the toBase64String() please open an issue and post the details(stacktrace and snippet code)

**Comment by victorsosa** [comment]
Now that I check I am thinking on remove toBase64String(); It has no meaning on the SVG interface.

**Comment by victorsosa** [comment]
@nicHoch GoodNEWS 
I finished this morning the SVGImage component, please check here is a snippet code about how to use it.
:tada: :tada: :tada: 
Since ver 1.1.0

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd"
      xmlns:svg="nativescript-svg" loaded="pageLoaded">
  <StackLayout>
    <!-- svg image tag-->
    <svg:SVGImage src="~/image/nativescript.svg" height="100" />
    <svg:SVGImage src="https://media4.giphy.com/media/3uyIgVxP1qAjS/200.svg" height="200" />
    <!--normal image tag-->
    <Image src="~/images/logo.svg" stretch ="none" />    
  </StackLayout> 
</Page>  
```

**Comment by victorsosa** [comment]
@nicHoch hey did you tested out?

**Comment by onury** [comment]
Didn't work for me. cannot find module.. tns v2.4.2

**Comment by ajkula** [comment]
wow it's really not working anything you say in the readme crashes the app...
shouldn't have installed it!

**Comment by datanotion** [comment]
Having the same problem on the Android side (module not found).  I think this should be reopened - thanks for your hard work @victorsosa!

**Comment by laxmisuresh** [comment]
@victorsosa 
# Still getting below error. Kindly help.

**### W/System.err(21498): Error: com.tns.NativeScriptException: Failed to find module: "nativescript-svg", relative to: app/tns_modules/
W/System.err(21498):     com.tns.Module.resolvePathHelper(Module.java:159)
W/System.err(21498):     com.tns.Module.resolvePath(Module.java:60)
W/System.err(21498):     com.tns.Runtime.runModule(Native Method)
W/System.err(21498):     com.tns.Runtime.runModule(Runtime.java:580)
W/System.err(21498):     com.tns.Runtime.run(Runtime.java:574)
W/System.err(21498):     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:33)
W/System.err(21498):     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
W/System.err(21498):     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
W/System.err(21498):     android.app.ActivityThread.access$1600(ActivityThread.java:175)
W/System.err(21498):     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
W/System.err(21498):     android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(21498):     android.os.Looper.loop(Looper.java:146)
W/System.err(21498):     android.app.ActivityThread.main(ActivityThread.java:5602)
W/System.err(21498):     java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(21498):     java.lang.reflect.Method.invoke(Method.java:515)**

**Comment by ajkula** [comment]
@victorsosa

Hello, if you manage to fix the issues, it'll be an amazing module for us to use!
I hope all the report displays how people need it... and be an encouragement.
As of now I have to forget about using SVGs in my NS app sadly.
Keep up the hard work!

**Comment by laxmisuresh** [comment]
@ajkula Yes exactly. We have decided to use PNG files.

**Comment by jakoguta** [comment]
@victorsosa its good to see a migration PR. However, the error is still visible. I am using angular and by just declaring `var ImageSourceSVGModule = require("nativescript-svg");` the app crashes. 

My `package.json` looks like this:

```
{
  "nativescript": {
    "id": "...",
    "tns-ios": {
      "version": "3.0.1"
    },
    "tns-android": {
      "version": "3.0.1"
    }
  },
  "dependencies": {
    "@angular/common": "~4.1.3",
    ...
    "nativescript-angular": "3.0.0",
    ...
    "nativescript-svg": "^1.3.0",
    ...
    "tns-core-modules": "3.0.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.1.3",
    "@ngtools/webpack": "~1.4.0",
     ...
    "typescript": "^2.3.4",
    "webpack": "^2.6.1",
    "webpack-sources": "^1.0.1"
  }
}

```

I deleted `platforms`, `node_modules` and `hooks` before installing my `deps` then I installed `tns plugin add nativescript-svg`.

**Comment by victorsosa** [comment]
v1.3.0 -- NS 3+ implementation and it will work with angular if you call registerElement before using it.

**Comment by mm-ns** [comment]
Could you please share how exactly to call the registerElement for those who may not be familiar with it? I have the same issue in {N} Angular 4:

`JS ERROR Error: Could not find module 'nativescript-svg'. Computed path '/var/mobile/Containers/Data/Application/9E7F66C7-C582-4BDD-A5F1-CE762DE35F89/Library/Application Support/LiveSync/app/tns_modules/nativescript-svg'.
Error while waiting for response from NativeScript runtime.`

Any help would be greatly appreciated.

**Comment by spierala** [comment]
Same issue here on Android.
PlugIn Version 1.3.4
