### ISSUE TITLE
Unable to find a target named `demo-App`

### ISSUE THREAD

**Issue by terreb** [peoplewareDo/nativescript-svg#14]
[!] Unable to find a target named `demo-App`, did find `...`.
Processing node_modules failed. Error: Command pod failed with exit code 1

Get this on "tns build ios".

nativescript-svg: 1.1.4
tns 2.5.4
tns-core-modules: 2.5.2
tns-ios: 2.5.0
Xcode: 8.2.1

**Comment by datanotion** [comment]
Just installed this and received the same error.  Any solution found @terreb?

**Comment by theAl** [comment]
Hi,
as written here: https://github.com/peoplewareDo/nativescript-svg/issues/7#issuecomment-297513414, I also receive the same error. Thanks for any help!

**Comment by victorsosa** [comment]
Please change the platform/ios/Podfile in the plugin to this:

`pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '2.x'`

and let me know if works.

**Comment by theAl** [comment]
Eh... yes, that's what I've done/written in the comment. That works until I rebuild the App.

**Comment by atrombet** [comment]
I am also experiencing this issue.

**Comment by lefoy** [comment]
Same for me

**Comment by victorsosa** [comment]
new release 1.3.0
