### ISSUE TITLE
Ns 3, Angular 4, webpack

### ISSUE THREAD

**Issue by dvdbrk** [peoplewareDo/nativescript-svg#15]
Hi again,

I am trying to make this work with NS 3, Angular 4 and Webpack AOT. But there are so many issues I have not idea what is wrong.

Running `npm run start-android-bundle --aot --display-error-details` (as per http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html) throws an error:

> ERROR  in ../\~/nativescript-svg/svg.common.js
Module not found: Error: Can't resolve 'ui/core/proxy' in 'C:\Users\dvdbrk\Native app\node_modules\nativescript-svg'
 @ ../\~/nativescript-svg/svg.common.js 8:12-36
 @ ../\~/nativescript-svg/svg.android.js
 @ ./app.component.ts
 @ ./app.component.ngfactory.ts
 @ ./app.module.ngfactory.ts
 @ ./main.aot.ts`

Is Ns 3 supported? Is webpack supported? Any ideas how to fix this?

**Comment by theAl** [comment]
I have almost the same error:
```
TypeError: Could not load view for: SVGImage.Error: Could not find module 'ui/core/proxy'.
```
Also using NS3 and Angular4 for an iOS app... Some help would be awesome!

**Comment by bradmartin** [comment]
https://github.com/peoplewareDo/nativescript-svg/pull/18 < this PR will support NS 3+ and support angular. The Webpack support might need some improved pieces to the plugin but should work fine.

**Comment by victorsosa** [comment]
new release 1.3.0

**Comment by victorsosa** [comment]
Support for Angular 4 coming soon on release 1.3.4
