### ISSUE TITLE
nativescript-svg will it work for typeScript

### ISSUE THREAD

**Issue by bjai** [peoplewareDo/nativescript-svg#16]
hi team 

can you please tell me how to include the SVG image in the typescript after installing the plugin 

`tns plugin add nativescript-svg`

and also tried to include the below code in the HTML but it doesn't work 

```
StackLayout>
        <Image src="~/images/1.svg" stretch ="none" />    
  </StackLayout>
``` 

It would be great if you help me with this

**Comment by victorsosa** [comment]
Like this:
`<svg:SVGImage src="~/image/nativescript.svg" height="100" />`

**Comment by laxmisuresh** [comment]
is it work for nativescript + angular2 framework ?

import * as elementRegistryModule from 'nativescript-angular/element-registry';
elementRegistryModule.registerElement("SVGImage", () => require("nativescript-svg").SVGImage);

<SVGImage src="~/image/nativescript.svg" height="100" ></SVGImage>

The above code will work? or currently no support for Angular2?

**Comment by vjoao** [comment]
@laxmisuresh why dont you test it and tell us?

**Comment by laxmisuresh** [comment]
@vjoao It is not working for me in NS3 environment.

**Comment by vjoao** [comment]
View plugins need some rework in order to adapt to the new View architecture present on NS3

**Comment by Jaishankarb** [comment]
can you update us on this issue

**Comment by bradmartin** [comment]
https://github.com/peoplewareDo/nativescript-svg/pull/18 < this PR will update for NS 3+ and it will work with angular if you call registerElement before using it.

**Comment by victorsosa** [comment]
new release 1.3.0
