### ISSUE TITLE
Failed to find module: "ui/core/proxy"

### ISSUE THREAD

**Issue by Hesamp** [peoplewareDo/nativescript-svg#17]
hi
error with svg
`java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.mobileapp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_modules/
`

**Comment by Hesamp** [comment]
check this [issue](https://github.com/bradmartin/nativescript-gif/issues/13)

plz update

**Comment by bradmartin** [comment]
https://github.com/peoplewareDo/nativescript-svg/pull/18 PR << fixes it for NS 3+

**Comment by victorsosa** [comment]
new release 1.3.0

**Comment by Hesamp** [comment]
but not work for me 
i remove platforme android and add platform 
build android 
but still have error 
see this image
http://titles.ir/wp-content/uploads/2017/06/ssss.png

**Comment by corebreaker** [comment]
Yes don't close the issue when the problem still exits !
