### ISSUE TITLE
Could not load view for: SVGImage.Error: Could not find module '../'

### ISSUE THREAD

**Issue by tobydeh** [peoplewareDo/nativescript-svg#26]
I'm getting the following error when using nativescript-svg with nativescript 3.3.0 and typescript 2.4.2:

Could not load view for: SVGImage.Error: Could not find module '../'

**Comment by mhadaily** [comment]
I have the same issue, might be related to #23

**Comment by victorsosa** [comment]
fix on release 1.3.5
