### ISSUE TITLE
Issue with the path

### ISSUE THREAD

**Issue by jdnichollsc** [peoplewareDo/nativescript-svg#28]
I think the path is incorrect: **require("../").SVGImage**
https://github.com/peoplewareDo/nativescript-svg/blob/a87237b97b59622d13b2ad4a4bb6e4c5f631cfcc/src/angular/nativescript-svg-module.ts#L12

What do you think to use **require("../svg").SVGImage** instead?
Thanks in advance

**Comment by victorsosa** [comment]
did you tested it? any Pull request is welcome

**Comment by victorsosa** [comment]
The .JS file where missing in the npm package
fix on release 1.3.5
