### ISSUE TITLE
Could not load view for SVGImage

### ISSUE THREAD

**Issue by waszqba** [peoplewareDo/nativescript-svg#30]
`Could not load view for: SVGImage.Error: com.tns.NativeScriptException: Failed to find module: "../", relative to: app/tns_modules/nativescript-svg/angular/` is the error thrown at me when trying to use your plugin with angular. Trace leads to `/angular/nativescript-svg-module.ts`'s `require("../").SVGImage` statement requiring a non-existent file.
Is there anything I can be doing wrong?

**Comment by wanpeng2008** [comment]
same issue. It seems that the author has no plan to fix it.

**Comment by victorsosa** [comment]
fix on release 1.3.5
