### ISSUE TITLE
Do you have support for nativescript-vue?

### ISSUE THREAD

**Issue by ricardoorellana** [peoplewareDo/nativescript-svg#31]
Hello, I was wondering if this plugin is supported on nativescript-vue. I have tried to register it as a plugin https://nativescript-vue.org/en/docs/getting-started/nativescript-plugins/ however it did not work, it always throw a module not found error.

`Module not found: Error: Can't resolve 'nativescript-svg' in '/Users/ricardoorellana/Documents/native_script_projects/castle-mobile/src'
 @ ./src/main.js 29:9-36`

**Comment by Rybak5611** [comment]
Experiencing same meme

**Comment by Rybak5611** [comment]
@ricardoorellana 
After few hours of suffering i found a solution. 
There is working fork made by teammaestro
``npm install @teammaestro/nativescript-svg``
``Vue.registerElement("SVGImage", () => require("@teammaestro/nativescript-svg").SVGImage)``

**Comment by ricardoorellana** [comment]
Thanks @Rybak5611 I am going to take a look to it!

**Comment by mennolp098** [comment]
@Rybak5611 Does not seem to work for me. I get passed the "Error: Can't resolve 'nativescript-svg'".
But after trying to load a page which has a SVGImage inside nothing happens. 
The page doesn't even get loaded and in the logs it did try to create the element but after that it just stops.

**Comment by ricardoorellana** [comment]
Ok great, then I am going to close this issue. Thank you for helping me.

**Comment by mikerockett** [comment]
@Rybak5611 Doesn't appear to work at all.

```
Error in nextTick: "TypeError: com.caverock.androidsvg.SVGImageView is not a constructor"
```

**Comment by mikerockett** [comment]
Apologies, it does appear to work after a platform refresh. 🙈 

Thanks :)
