### ISSUE TITLE
Styling SVG with css - Is it possible ? 

### ISSUE THREAD

**Issue by tonyawad88** [peoplewareDo/nativescript-svg#4]
Hello,

Do you think there's any chance we can style the svg from css within nativescript ?

Thank you !

**Comment by victorsosa** [comment]
Yes, I do. I don't have any idea right now, of how to do it. Any PR are welcome too.

**Comment by victorsosa** [comment]
But you can style (static) it and try it render it.

**Comment by tonyawad88** [comment]
True. I was able to style it statically. I noticed also the height and width must be specified on the svg otherwise it throws an error.

Anyhow thank you for this plugin. It definitely helps a lot.

**Comment by victorsosa** [comment]
I glad you like XD, Thank you.

**Comment by victorsosa** [comment]
svg clip-path is another way to implement this too.
