### ISSUE TITLE
Using this plugin with Angular flavor of nativescript

### ISSUE THREAD

**Issue by danielgek** [peoplewareDo/nativescript-svg#7]
Hi i'm trying to use this plugin with angular flavor of nativescript, but unfortunately it doesn't work.

this is how i imported the SVGImage:

```typescript
import { registerElement } from "nativescript-angular/element-registry";
registerElement("SvgImage", () => require("nativescript-svg").SVGImage);
```
error trace: 
```
EXCEPTION: Uncaught (in promise): Error: Error in ...page.component.html:11:3 caused by: Could not load view for: SvgImage.TypeError: Cannot read property 'id' of undefined
ORIGINAL STACKTRACE:
Error: Uncaught (in promise): Error: Error in ...page.component.html:11:3 caused by: Could not load view for: SvgImage.TypeError: Cannot read property 'id' of undefined

```

if i have some time i will try to understand the error and make a PR, but i can't right now

**Comment by dvdbrk** [comment]
@danielgek I am having the same issue. What do you use in your html template?

**Comment by danielgek** [comment]
@dvdbrk 
```html
<SvgImage src="~/image/nativescript.svg" height="100" />
```

something like this

**Comment by dvdbrk** [comment]
Yes - that is what I am using and I still can't get it to work. Does this plugin work at all on android with angular?

**Comment by danielgek** [comment]
@dvdbrk i think it doesn't, the native libs are outdated afaik

**Comment by danielgek** [comment]
@dvdbrk  actually the libs are up to date, i will take a look later, let's see if i can get it to work

**Comment by eleddie** [comment]
Any update on this issue?

**Comment by jruef** [comment]
Hey there i have  get a different error with the plugin: `Can't find variable: SVGKImage`. I used:

```
import { registerElement } from "nativescript-angular/element-registry";
registerElement("SvgImage", () => require("nativescript-svg").SVGImage);
```
and
```
<SvgImage src="~/assets/icons/icon.svg" height="100"></SvgImage>
```

**Comment by eleddie** [comment]
+1

**Comment by dembal1990** [comment]
+1

**Comment by victorsosa** [comment]
@danielgek  
I think this issue could be cause by this; explained in this stackoverflow article:
https://stackoverflow.com/questions/40482785/angular-2-uncaught-typeerror-cannot-read-property-id-of-undefined
Can I see you page.component.html??

**Comment by danielgek** [comment]
@victorsosa my setup has changed since last time i wrote the issue and because i was short on time i ended up using an alternative.

i'm not sure if the issue this is related to that st question, nativescript uses commonjs as long as i remember

**Comment by GrEg00z** [comment]
The plugin doesn't working at all for me.
I use Nativescript with Angular

### If I only use in my code  :

`var ImageSourceSVGModule = require("nativescript-svg");`

I get this error :

`TypeError: Cannot read property 'id' of undefined ....... /app/tns_modules/ui/styling/style.js, line: 1114`

**The function concerned in style.js is :**
`function registerHandler(property, handler, className) {`
    `......`
        `_registeredHandlers[property.id] = handlerRecord;`
   `.......`
`}`
Where **property.id** is undefined !

### Also If I use in my code :

`import { registerElement } from "nativescript-angular/element-registry";`
`registerElement("SvgImage", () => require("nativescript-svg").SVGImage);`

I get this error when I try to add SvgImage component to my view :

`SvgImage.TypeError: Cannot read property 'id' of undefined`

**Comment by joshcomley** [comment]
I have the same issue, would love a solution!

**Comment by jerkly** [comment]
Same issue for me. Problem only with android.

`TypeError: Cannot read property 'id' of undefined`
`/app/tns_modules/ui/styling/style.js, line: 1114`

With quick look I found that problem is in this part

`svg.android.ts:246`
```
public static registerHandlers() {
    // Use the same handler for all background/border properties
    // Note: There is no default value getter - the default value is handled in background.ad.onBackgroundOrBorderPropertyChanged

    style.registerHandler(style.borderRadiusProperty, new style.StylePropertyChangedHandler(
        ImageStyler.setBorderRadiusProperty,
        ImageStyler.resetBorderRadiusProperty), "SVGImage");

    style.registerHandler(style.borderWidthProperty, new style.StylePropertyChangedHandler(
        ImageStyler.setBorderWidthProperty,
        ImageStyler.resetBorderWidthProperty), "SVGImage");
}
```

Looks like `borderRadiusProperty` and `borderWidthProperty` logic has been modified a little since `tns-core-modules@2.0.1`

**Solution worked for me:**
`typescript@2.1.6`
`nativescript-angular@1.4.0`
`tns-core-modules@2.5.0`

Modify `registerHandlers` method in `svg.android.ts:246`.

```
public static registerHandlers() {
    style.registerHandler(style.borderTopWidthProperty, new style.StylePropertyChangedHandler(ImageStyler.setBorderWidthProperty, ImageStyler.resetBorderWidthProperty), "SVGImage");
    style.registerHandler(style.borderRightWidthProperty, new style.StylePropertyChangedHandler(ImageStyler.setBorderWidthProperty, ImageStyler.resetBorderWidthProperty), "SVGImage");
    style.registerHandler(style.borderBottomWidthProperty, new style.StylePropertyChangedHandler(ImageStyler.setBorderWidthProperty, ImageStyler.resetBorderWidthProperty), "SVGImage");
    style.registerHandler(style.borderLeftWidthProperty, new style.StylePropertyChangedHandler(ImageStyler.setBorderWidthProperty, ImageStyler.resetBorderWidthProperty), "SVGImage");

    style.registerHandler(style.borderTopLeftRadiusProperty, new style.StylePropertyChangedHandler(ImageStyler.setBorderRadiusProperty, ImageStyler.resetBorderRadiusProperty), "SVGImage");
    style.registerHandler(style.borderTopRightRadiusProperty, new style.StylePropertyChangedHandler(ImageStyler.setBorderRadiusProperty, ImageStyler.resetBorderRadiusProperty), "SVGImage");
    style.registerHandler(style.borderBottomRightRadiusProperty, new style.StylePropertyChangedHandler(ImageStyler.setBorderRadiusProperty, ImageStyler.resetBorderRadiusProperty), "SVGImage");
    style.registerHandler(style.borderBottomLeftRadiusProperty, new style.StylePropertyChangedHandler(ImageStyler.setBorderRadiusProperty, ImageStyler.resetBorderRadiusProperty), "SVGImage");
}
```

@victorsosa, it wiil be good, if you check it and publish a new version to npm.

Also, I suggest to do not ignore *.d.ts files in publishing process, because they are **very** useful in IDE autocomplete.

**Comment by demetrio812** [comment]
Hello,
I'm trying to use the plugin on iOS with the latest version of TNS but it doesn't seem to be working, it doesn't show any error too

Anybody got it working on iOS?

Thanks,
Dem

**Comment by AbdallahBedir** [comment]
+1

**Comment by victorsosa** [comment]
@demetrio812 fix comming on v1.1.4 for iOS

**Comment by victorsosa** [comment]
@jerkly fix is comming on v1.1.4

**Comment by victorsosa** [comment]
fixed

**Comment by hrandika** [comment]
After install (v 1.1.4) I get this,

Installing pods...
Analyzing dependencies
[!] Unable to find a target named `demo-App`, did find `nativescript`.

**Comment by ignaciofuentes** [comment]
I ran into the same issue as @hrandika

**Comment by dvdbrk** [comment]
Same issue still exists on Android, 1.1.4

**Comment by theAl** [comment]
Hi @victorsosa,
I have the same issue as @hrandika and the other guys. Please can have a look, why the `Podfile` was changed in commit https://github.com/peoplewareDo/nativescript-svg/commit/36693dd3a272e7c33459ccaca26abf0adcce6cc1#diff-40f8348dee20e6ad0f55410856067c9d. If I revert this commit, it works again... thanks!

**Comment by laxmisuresh** [comment]
Still in 1.1.4 version used to get this issue;

JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'id' of undefined
JS: ORIGINAL STACKTRACE:
JS: Error: Uncaught (in promise): TypeError: Cannot read property 'id' of undefined

Kindly let me know when the issue will be fixed. 

Thanks for your effort.

**Comment by Igor912** [comment]
nativescript-svg works with Angular.

Just run and check nativescript-svg angular demo app.

BUT
you need to add few changes to this project before the run:
in package.json replace `"nativescript-svg": "../src"` with `"@teammaestro/nativescript-svg": "0.0.1"`.
in app.module.ts replace `import { NativeScriptSvgModule } from "nativescript-svg/angular";` with `import { NativeScriptSvgModule } from "@teammaestro/nativescript-svg/angular";`

**Comment by alejandro-heredia-coderoad-com** [comment]
Thank you @Ihor912, it's working with your changes on the package.json and the import.

**Comment by hackerunet** [comment]
Sorry, this is not working for me, this is my system:
$ tns --version
3.4.2
$ node -v
v9.6.1

"@teammaestro/nativescript-svg": "^1.0.1",
"nativescript-angular": "~5.2.0",
 
```
S: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ANGULAR BOOTSTRAP DONE. 24450
Successfully synced application org.nativescript.mxamicasa on device emulator-5554.
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getFromInputStream' of undefined
JS: TypeError: Cannot read property 'getFromInputStream' of undefined
JS:     at ImageSourceSVG.loadFromFile (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@teammaestro/nativescript-svg/svg.js:51:54)
JS:     at SVGImage._createImageSourceFromSrc (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@teammaestro/nativescript-svg/svg.common.js:65:32)
JS:     at valueChanged (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@teammaestro/nativescript-svg/svg.common.js:13:149)
JS:     at SVGImage.Property.set [as src] (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/tns-core-modules/ui/core/properties/properties.js:104:25)
JS:     at ViewUtil.setPropertyInternal (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/nativescript-angular/view-util.js:268:32)
JS:     at ViewUtil.setProperty (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/nativescript-angular/view-util.js:247:18)
JS:     at EmulatedRenderer.NativeScriptRenderer.setAttribute (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/nativescript-angular/renderer.js:131:30)
JS:     at DebugRenderer2.setAttribute (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/core/bundles/core.umd.js:15337:23)
JS:     at createElement (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/core/bundles/core.umd.js:10592:22)
JS:     at createViewNodes (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/core/bundles/core.umd.js:13741:61)
JS:     at callViewAction (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/core/bundles/core.umd.js:14214:13)
JS:     at execComponentViewsAction (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/core/bundles/core.umd.js:14123:13)
JS:     at createViewNodes (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/core/bundles/core.umd.js:13808:5)
JS:     at createRootView (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/core/bundles/core.umd.js:13669:5)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/core/bundles/core.umd.js:15094:42)
JS: ERROR Error: Uncaught (in promise): Error: Outlet is not activated
JS: Error: Outlet is not activated
JS:     at PageRouterOutlet.detach (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:190:19) [angular]
JS:     at ActivateRoutes.detachAndStoreRouteSubtree (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/router/bundles/router.umd.js:5714:64) [angular]
JS:     at ActivateRoutes.deactivateRouteAndItsChildren (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/router/bundles/router.umd.js:5695:18) [angular]
JS:     at ActivateRoutes.deactivateRoutes (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/router/bundles/router.umd.js:5679:22) [angular]
JS:     at file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/router/bundles/router.umd.js:5639:19 [angular]
JS:     at Array.forEach (native) [angular]
JS:     at ActivateRoutes.deactivateChildRoutes (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/router/bundles/router.umd.js:5637:29) [angular]
JS:     at ActivateRoutes.activate (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/router/bundles/router.umd.js:5617:14) [angular]
JS:     at file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/@angular/router/bundles/router.umd.js:5533:18 [angular]
JS:     at SafeSubscriber._next (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/rxjs/Observable.js:225:21) [angular]
JS:     at SafeSubscriber.__tryOrSetError (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/rxjs/Subscriber.js:248:16) [angular]
JS:     at SafeSubscriber.next (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/rxjs/Subscriber.js:188:27) [angular]
JS:     at Subscriber._next (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/rxjs/Subscriber.js:126:26) [angular]
JS:     at Subscriber.next (file:///data/data/org.nativescript.mxamicasa/files/app/tns_modules/rxjs/Subscriber.js:90:18) [angular]

```

**Comment by victorsosa** [comment]
release 1.3.5 just fix the missing .JS file in the NPM package
