### ISSUE TITLE
System.err: remove failed: EACCESS 

### ISSUE THREAD

**Issue by jonathan-casarrubias** [peoplewareDo/nativescript-svg#9]
Hello,

I'm trying to use this module but just by requiring the package the app is broken.

````js
var ImageSourceSVGModule = require("nativescript-svg");
````

After adding that line anywhere in my app I get the following:

````sh
System.err: remove failed: EACCES (Permission denied): data/local/tmp/org.my.app/sync/tns_modules/nativescript-svg
````

It obviously is saying there is no permissions to do something into that directory not sure what is trying to do, or if I need to enable something? I don't see anything related in the documentation.

I really would appreciate if you provide with some directions.

Regards
Jon

**Comment by victorsosa** [comment]
can you retry using the v1.1.4 and let me know

**Comment by victorsosa** [comment]
new release 1.3.0
